rate_my_teammates/config/routes.rb
RateMyTeammate::Application.routes.draw do


    root :to => redirect('/users')

    get 'auth', to: 'sessions#auth', as: :auth # auth_path

    get '/users/search', to: 'users#search', as: :search

    get 'login', to: 'sessions#new', as: :login
    post 'verify', to: 'sessions#verify', as: :verify
    get 'logout', to: 'sessions#destroy', as: :logout


    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :update] do
        resources :reviews, only: [:index, :new, :create]
        resources :skills, only: [:index, :new, :create]
    end

    resources :endorsements, only: [:new, :create]


end

rate_my_teammates/app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

rate_my_teammates/app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Rate My Teammates!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  
  <header class="navbar navbar-light" style="background-color: #e6f3fc;">
  <div class="container">
    <nav>
      <font size="+1" color=white><%= link_to "Home", root_path %>&nbsp;&nbsp;
      <% if current_user.nil? %>    
          <%= link_to "Sign In", login_path %></font>
      <% else %>
          <%= link_to "Profile", user_path(current_user) %>&nbsp;&nbsp;
          <%= link_to "Sign Out", logout_path %></font>
      <% end %>
    </nav>
  </div>
</header>
  
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
  <br><br>

</html>