rate_my_teammates/config/routes.rb
RateMyTeammate::Application.routes.draw do


    root :to => redirect('/users')

    get 'auth', to: 'sessions#auth', as: :auth # auth_path

    get '/users/search', to: 'users#search', as: :search

    get 'login', to: 'sessions#new', as: :login
    post 'verify', to: 'sessions#verify', as: :verify
    get 'logout', to: 'sessions#destroy', as: :logout


    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :update] do
        resources :reviews, only: [:index, :new, :create]
        resources :skills, only: [:index, :new, :create]
    end

    resources :endorsements, only: [:new, :create]


end

rate_my_teammates/app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  has_many :endorsements
end

rate_my_teammates/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def new
    @user = User.find_by(uni: params[:user_uni])
    @skill = @user.skills.build
  end

  def create
    user_uni = params[:skill][:user_uni]
    @user = User.find_by(uni: user_uni)

    # if User.find_by(uni: params[:review][:reviewer_uni]) == nil:
    #  flash[:notice] = "Commentor Uni empty or not exsist"

    if params[:skill][:name] == ""
      flash[:warning] = "Skill name cannot be empty"
      redirect_to new_user_skill_path(:user_uni => user_uni)
    else
      skill_params = params[:skill].except(:user_uni)
      @skill = @user.skills.create!(:name => params[:skill][:name])
      if @skill.save
        redirect_to user_path(@user)
      # else
      #   render "users/show"
      end
    end
  end
end

rate_my_teammates/app/helpers/skills_helper.rb
module SkillsHelper
end

rate_my_teammates/app/views/skills/_form.html.erb
<%= form_for [@user, @skill] do |form| %>
  <p>
    <%= form.label :skill_name, "Skill Name"  %><br>
    <%= form.text_field :name %>
  </p>

  <%= form.hidden_field :user_uni, :value => @user.uni %><br><br>
  <%= form.submit 'Add Skill', :class => 'btn btn-dark btn-outline-light' %>
  <%= link_to "Back", user_path(@user), :class => 'btn btn-light btn-outline-dark' %>
<% end %>

rate_my_teammates/app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

rate_my_teammates/app/views/skills/endorse.html.erb
<br><br>
<h2 style="font-family:Verdana; font-weight:600;" >New Skill For <%= @user.name %></h2>
<br>

<%= render "form" %>

<%= link_to "Back", user_path(@user) %>

rate_my_teammates/app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Endorser</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.endorser %></td>
        <td><%= skill.user %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

rate_my_teammates/app/views/skills/new.html.erb
<style>
.login { 
  margin: 30px auto;
  padding: 20px 50px 20px;
  width: 650px;
  background: white;
  border-radius: 10px;
  box-shadow: 0 0 200px rgba(255, 255, 255, 0.5), 0 1px 2px rgba(0, 0, 0, 0.3);
}

body {
  background: #DCDDDF;
}

</style>
<center>
<br><br>
<div class="login">
<h2 style="font-family:Verdana; font-weight:600;" >New Skill For <%= @user.name %></h2>
<br>

<%= render "form" %>
</div>
</center>

rate_my_teammates/app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Endorser:</strong>
  <%= @skill.endorser %>
</p>

<p>
  <strong>User:</strong>
  <%= @skill.user %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>