rate_my_teammates/config/routes.rb
RateMyTeammate::Application.routes.draw do


    root :to => redirect('/users')

    get 'auth', to: 'sessions#auth', as: :auth # auth_path

    get '/users/search', to: 'users#search', as: :search

    get 'login', to: 'sessions#new', as: :login
    post 'verify', to: 'sessions#verify', as: :verify
    get 'logout', to: 'sessions#destroy', as: :logout


    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :update] do
        resources :reviews, only: [:index, :new, :create]
        resources :skills, only: [:index, :new, :create]
    end

    resources :endorsements, only: [:new, :create]


end

rate_my_teammates/app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :skills
  has_many :endorsements
  validates :uni, presence: true, uniqueness: true
end

rate_my_teammates/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    # flash[:notice] = nil
    @user = User.find(params[:id]) # look up user by unique ID
    # will render app/views/users/show.<extension> by default
    time_management_lst = []
    User.find(params[:id]).reviews.each do |review|
        time_management_lst << review.time_management
    end
    @time_management = time_management_lst.reduce(:+).to_f / time_management_lst.size
    communication_lst = []
    User.find(params[:id]).reviews.each do |review|
        communication_lst << review.communication
    end
    @communication = communication_lst.reduce(:+).to_f / communication_lst.size
    reliability_lst = []
    User.find(params[:id]).reviews.each do |review|
        reliability_lst << review.reliability
    end
    @reliability = reliability_lst.reduce(:+).to_f / reliability_lst.size
    critical_thinking_lst = []
    User.find(params[:id]).reviews.each do |review|
        critical_thinking_lst << review.critical_thinking
    end
    @critical_thinking = critical_thinking_lst.reduce(:+).to_f / critical_thinking_lst.size
    collaboration_lst = []
    User.find(params[:id]).reviews.each do |review|
        collaboration_lst << review.collaboration
    end
    @collaboration = collaboration_lst.reduce(:+).to_f / collaboration_lst.size

  end

  def index
    @users = User.all
  end

  def search
    @users = User.where(uni: params[:uni])

    if params[:uni].length == 0
        flash[:warning] = "No UNI entered."
        @users = User.all
    elsif params[:uni].length > 0 and @users.length == 0
        flash[:warning] = "UNI not in record."
    else
        flash[:notice] = "Found 1 result"
    end

    render :index

  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to(@user) }
        format.json { respond_with_bip(@user) }
      else
        # format.html { render :action => "edit" }
        # format.json { respond_with_bip(@user) }
      end
  end
end
  # def new
  #   default: render 'new' template
  # end

  # def create
  #   @user = User.create!(user_params)
  #   flash[:notice] = "#{@movie.title} was successfully created."
  #   redirect_to movies_path
  # end

  # def edit
  #   @user = User.find params[:id]
  # end

  # def update
  #   @movie = Movie.find params[:id]
  #   @movie.update_attributes!(movie_params)
  #   flash[:notice] = "#{@movie.title} was successfully updated."
  #   redirect_to movie_path(@movie)
  # end

  # def destroy
  #   @movie = Movie.find(params[:id])
  #   @movie.destroy
  #   flash[:notice] = "Movie '#{@movie.title}' deleted."
  #   redirect_to movies_path
  # end

#   private
#   # Making "internal" methods private is not required, but is a common practice.
#   # This helps make clear which methods respond to requests, and which ones do not.
   def user_params
     params.require(:user).permit(:uni, :name, :description, :summary, :search, :self_communication,:self_time_management, :self_reliability, :self_collaboration, :self_critical_thinking)
   end

end

rate_my_teammates/app/views/users/404.html.erb
<h> 404 Page not found <h>

rate_my_teammates/app/views/users/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<br>
<br>
<center>
<img src="https://1ns4r23y1yed2lbkso2b4lwq-wpengine.netdna-ssl.com/wp-content/uploads/2019/05/7-traits-unstoppable-teams-infographic-thumbnail-1080x675.jpg" alt="image" style="width:400px;height:250px;">
</center>
<br>
<center>
<h2 style="font-family:Verdana; font-weight:600;" >Rate My Teammates</h2>
    
<br>
    
<% if current_user.nil? %> 
    Please sign in to activate search / review adding / skill adding features.
<% else %>
    <%= form_tag("/users/search", method: :get) do %>
        <%= text_field_tag :uni, params[:uni], options = {style:"width:700px", placeholder:"Search by UNI"}%>
        <%= submit_tag ("Search")%>
    <% end %>
<% end %>
</center>

<br>
<br>
<table class="table table-striped col-md-12" id="users">

  <h4> All Users </h4>
  <br>
  <thead>
    <tr>
      <th style="width:25%;">UNI</th>
      <th style="width:25%;">Name</th>
      <th style="width:25%;">Program</th>
      <th style="width:25%;">Reviews</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.uni %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.description %>
        </td>
        <td>
          <%= link_to "More about #{user.name}", user_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rate_my_teammates/app/views/users/new.html.erb
<p id=”alert”><%= alert %></p>
<style>
.login { 
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -70%);
  margin: 30px auto;
  padding: 20px 50px 20px;
  width: 450px;
  background: white;
  border-radius: 10px;
  box-shadow: 0 0 200px rgba(255, 255, 255, 0.5), 0 1px 2px rgba(0, 0, 0, 0.3);
}

body {
  background: #0ca3d2;
}
.button{
  background: #cde5ef;
  width: 200px;
}
</style>
<body>
<center>
  <div class="login">
    <h2 style="font-family:Verdana; font-weight:600;" >Login</h2><br><br>

  Our projoect aims to assist Columbia Students with their work. We currently only accepts columbia UNIs.<br><br><br>


<%= form_tag verify_path do |form| %>
    <%= text_field_tag :uni, params[:uni], options = {style:"width:200px"}%><br><br>
    <%= submit_tag ("Sign In"), :class => 'button'%>
<% end %>
  </div>
</center>
</body>

rate_my_teammates/app/views/users/search.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Users</h2>

<!-- add search bar here -->

<h4> Search </h4>

<table class="table table-striped col-md-12" id="users">
  <thead>
    <tr>
      <th style="width:25%;">UNI</th>
      <th style="width:25%;">Name</th>
      <th style="width:25%;">Program</th>
      <th style="width:25%;">Reviews</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.uni %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.description %>
        </td>
        <td>
          <%= link_to "More about #{user.name}", user_path(user.uni) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rate_my_teammates/app/views/users/show.html.erb
<!--  app/views/movies/show.html.erb -->
<!-- Reference for the chart: https://github.com/styd/apexcharts.rb#radar-chart-1 -->
<br><br>
<h2 style="font-family:Verdana; font-weight:600;" >
    <% if !current_user.nil? and current_user.uni == @user.uni %>
        <%= best_in_place @user, :name, :as => :input, :place_holder => "Tell us who you are!" , :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit_#{@user.uni}" %>
        <button type="button" class="btn btn-link" id="edit_<%= @user.uni %>">Edit</button>
    <% else %>
        <%= @user.name %>
    <% end %>
</h2>
<br>

<ul id="details" style="font-family:Verdana;font-size:105%;">
  <li>
    <strong>UNI:</strong>
    <%= @user.uni %>
  </li>
  <li>
  <strong>Program:</strong>
    <% if !current_user.nil? and current_user.uni == @user.uni %>
        <%= best_in_place @user, :description, :as => :input, :place_holder => "Tell us what you study!" , :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit2_#{@user.uni}" %>
        <button type="button" class="btn btn-link" id="edit2_<%= @user.uni %>">Edit</button>
    <% else %>
        <%= @user.description %>
    <% end %>
    </li>
  <li>
  <strong>Summary:</strong>
    <% if !current_user.nil? and current_user.uni == @user.uni %>
        <%= best_in_place @user, :summary, :type => :textarea, :place_holder => "Write something we need to know about you!", :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit3_#{@user.uni}" %>
        <button type="button" class="btn btn-link" id="edit3_<%= @user.uni %>">Edit</button>
    <% else %>
        <% p(@user) %>
        <%= @user.summary %>
    <% end %>
    </li>
</ul>
<div class="row" style="font-family:Verdana;font-size:105%;">
  <div class="column">
    <strong>General Skills:</strong>
     <% radar_series = [
      {
        name: "Self Evaluation",
        data: { "Communication"=>@user.self_communication, "Time Management"=>@user.self_time_management, "Reliability"=>@user.self_reliability, "Collaboration"=>@user.self_collaboration, "Critical Thinking"=>@user.self_critical_thinking}
      },
      {
        name: "Peer Evaluation",
        data: { "Communication"=>@communication, "Time Management"=>@time_management, "Reliability"=>@reliability, "Collaboration"=>@collaboration , "Critical Thinking"=>@critical_thinking}
      }
    ] %>
    <%= radar_chart(
      radar_series,
      {markers: {size: 4}, theme: 'palette1'}
    ) %>



    <% if !current_user.nil? and current_user.uni == @user.uni %>
      <strong>Self Evaluation Details (1 poor ~ 5 great):</strong>
      <li>Communication: <%= best_in_place @user, :self_communication, :as => :select, :collection =>["1","2","3","4","5"],:place_holder => "Please rate yourself", :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit4_#{@user.uni}" %><button type="button" class="btn btn-link" id="edit4_<%= @user.uni %>">Edit</button></li>
      <li>Time Management: <%= best_in_place @user, :self_time_management, :as => :select, :collection =>["1","2","3","4","5"],:place_holder => "Please rate yourself", :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit5_#{@user.uni}" %><button type="button" class="btn btn-link" id="edit5_<%= @user.uni %>">Edit</button></li>
      <li>Reliability: <%= best_in_place @user, :self_reliability, :as => :select, :collection =>["1","2","3","4","5"],:place_holder => "Please rate yourself",  :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit6_#{@user.uni}" %><button type="button" class="btn btn-link" id="edit6_<%= @user.uni %>">Edit</button></li>
      <li>Collaboration: <%= best_in_place @user, :self_collaboration, :as => :select, :collection =>["1","2","3","4","5"],:place_holder => "Please rate yourself",  :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit7_#{@user.uni}" %><button type="button" class="btn btn-link" id="edit7_<%= @user.uni %>">Edit</button></li>
      <li>Critical Thinking: <%= best_in_place @user, :self_critical_thinking, :as => :select, :collection =>["1","2","3","4","5"],:place_holder => "Please rate yourself",  :ok_button => 'Save', :cancel_button => 'Cancel', :activator => "#edit8_#{@user.uni}" %><button type="button" class="btn btn-link" id="edit8_<%= @user.uni %>">Edit</button></li>

    <% end %>




  </div>


  <div class="column">
    <strong>Other Skills:</strong>
    <% @user.skills.each do |skill| %>
      <li><strong><%= skill.name %></strong> &nbsp;&nbsp; <%= skill.endorsements.count %>
      <%= (skill.endorsements.count) < 2 ? 'Endorsement' : 'Endorsements'%> &nbsp;&nbsp;
      <button type="button" class="btn btn-default btn-sm">
      <% if !current_user.nil? %>
          <%= button_to 'Endorse', endorsements_path, params: {user_id: @user, user_uni: @user.uni, endorser_id: current_user.id, skill_id: skill.id}, method: :post%>
      <% end %>
      </button></li>
    <% end %>
  </div>
</div>
<br>
<h5 style="font-family:Verdana;font-weight:600;">Comments From Previous Teammates</h5>

<% @user.reviews.each do |review| %>
  <br>
  <p>
    <strong>Reviewer:</strong>
    <%= review.reviewer_uni %>
    &nbsp;&nbsp;
    <strong>Class:</strong>
    <%= review.course_taken_together %>
  </p>

  <p style="border:2px; border-radius: 25px;border-style:solid; border-color:#000000; padding: 1em;">
    <%= review.content %>
  </p>
<% end %>
<br>
<div class="row" >
  <%= link_to 'Back To User List', users_path, :class => 'btn btn-light btn-outline-dark' %>
  &nbsp;&nbsp;
  <% if !current_user.nil? and current_user.uni != @user.uni %>
      <%= link_to "Add A Review", new_user_review_path(user_id: @user, user_uni: @user.uni), :class => 'btn btn-dark btn-outline-light' %>
      &nbsp;&nbsp;
  <% end %>
  <% if !current_user.nil? %>
      <%= link_to "Add A Skill", new_user_skill_path(user_id: @user, user_uni: @user.uni), :class => 'btn btn-dark btn-outline-light' %>
  <% end %>
</div>
<br>
<br>